/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults, } from "@stencil/router";
export namespace Components {
    interface ClFooter {
    }
    interface ClHeader {
    }
    interface ClHome {
    }
    interface ClMain {
    }
    interface ClModal {
        "title": string;
    }
    interface ClProfile {
        "match": MatchResults;
    }
    interface ClRoot {
    }
}
declare global {
    interface HTMLClFooterElement extends Components.ClFooter, HTMLStencilElement {
    }
    var HTMLClFooterElement: {
        prototype: HTMLClFooterElement;
        new (): HTMLClFooterElement;
    };
    interface HTMLClHeaderElement extends Components.ClHeader, HTMLStencilElement {
    }
    var HTMLClHeaderElement: {
        prototype: HTMLClHeaderElement;
        new (): HTMLClHeaderElement;
    };
    interface HTMLClHomeElement extends Components.ClHome, HTMLStencilElement {
    }
    var HTMLClHomeElement: {
        prototype: HTMLClHomeElement;
        new (): HTMLClHomeElement;
    };
    interface HTMLClMainElement extends Components.ClMain, HTMLStencilElement {
    }
    var HTMLClMainElement: {
        prototype: HTMLClMainElement;
        new (): HTMLClMainElement;
    };
    interface HTMLClModalElement extends Components.ClModal, HTMLStencilElement {
    }
    var HTMLClModalElement: {
        prototype: HTMLClModalElement;
        new (): HTMLClModalElement;
    };
    interface HTMLClProfileElement extends Components.ClProfile, HTMLStencilElement {
    }
    var HTMLClProfileElement: {
        prototype: HTMLClProfileElement;
        new (): HTMLClProfileElement;
    };
    interface HTMLClRootElement extends Components.ClRoot, HTMLStencilElement {
    }
    var HTMLClRootElement: {
        prototype: HTMLClRootElement;
        new (): HTMLClRootElement;
    };
    interface HTMLElementTagNameMap {
        "cl-footer": HTMLClFooterElement;
        "cl-header": HTMLClHeaderElement;
        "cl-home": HTMLClHomeElement;
        "cl-main": HTMLClMainElement;
        "cl-modal": HTMLClModalElement;
        "cl-profile": HTMLClProfileElement;
        "cl-root": HTMLClRootElement;
    }
}
declare namespace LocalJSX {
    interface ClFooter {
    }
    interface ClHeader {
    }
    interface ClHome {
    }
    interface ClMain {
    }
    interface ClModal {
        "title"?: string;
    }
    interface ClProfile {
        "match"?: MatchResults;
    }
    interface ClRoot {
    }
    interface IntrinsicElements {
        "cl-footer": ClFooter;
        "cl-header": ClHeader;
        "cl-home": ClHome;
        "cl-main": ClMain;
        "cl-modal": ClModal;
        "cl-profile": ClProfile;
        "cl-root": ClRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cl-footer": LocalJSX.ClFooter & JSXBase.HTMLAttributes<HTMLClFooterElement>;
            "cl-header": LocalJSX.ClHeader & JSXBase.HTMLAttributes<HTMLClHeaderElement>;
            "cl-home": LocalJSX.ClHome & JSXBase.HTMLAttributes<HTMLClHomeElement>;
            "cl-main": LocalJSX.ClMain & JSXBase.HTMLAttributes<HTMLClMainElement>;
            "cl-modal": LocalJSX.ClModal & JSXBase.HTMLAttributes<HTMLClModalElement>;
            "cl-profile": LocalJSX.ClProfile & JSXBase.HTMLAttributes<HTMLClProfileElement>;
            "cl-root": LocalJSX.ClRoot & JSXBase.HTMLAttributes<HTMLClRootElement>;
        }
    }
}
